baseurl = "ceres/"
languageCode = "en-US"
title = "Anaya Hall"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"


[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "IMG_2248.jpg"
  author = "Anaya Hall"
  description = "Homepage for Anaya Hall, MSc"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "anayahall"
  Email         = "anayahall@berkeley.edu"
  Twitter       = "anayahall"
  LinkedIn      = "username"
  Stackoverflow = "username"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "CV"
  identifier = "resume"
  weight = 300
  url = "/resume/"
